# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bdf38f5089abb063842d2a1662bac460f8cbd07ee67e812fee69e42e1fb1341bee663e61acbe1cfe0c793144f995dc277558c78bd2c72c505abc43e80da7338

test:
  secret_key_base: 1f4762cd24874f8124483a56b69a6a6c83c555ad0395bc652a25f235e492712006b6065a36d8a88425d1a5a03b872bc5aef90c65bd124a4ddd7a58ca2f35094a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
